const firstThemeBtn = document.querySelector('#first');
const secondThemeBtn = document.querySelector('#second');
const thirdThemeBtn = document.querySelector('#third');
const ballBtn = document.querySelector('.ball');
let bodyBackgroundColor = document.querySelector('body');
let lastKey = document.querySelector('#last');
/*let buttonKey = document.querySelector('.number')*/


firstThemeBtn.addEventListener('change', () => { ballBtn.style.left = '4px';
bodyBackgroundColor.style.backgroundColor = 'hsl(222, 26%, 31%)';
bodyBackgroundColor.style.color = '#fff';
document.querySelector('.toggle-btn').style.backgroundColor='hsl(224, 36%, 20%)';
document.querySelector('.calc').style.backgroundColor='hsl(224, 36%, 15%)';
ballBtn.style.backgroundColor = 'hsl(6, 63%, 50%)';
document.querySelector('.grid-container').style.backgroundColor = 'hsl(223, 31%, 20%)';
/*buttonKey.style.backgroundColor = 'hsl(30, 25%, 89%)';
buttonKey.style.color = 'hsl(221, 14%, 31%)';
buttonKey.style.boxShadow = 'inset -0px -3px gray';*/
document.querySelector('.remove').style.backgroundColor = 'hsl(225, 21%, 49%)';
document.querySelector('.remove').style.boxShadow = 'inset -0px -5px hsl(224, 28%, 35%)';
document.querySelector('.reset').style.backgroundColor = 'hsl(225, 21%, 49%)';
document.querySelector('.reset').style.boxShadow = 'inset -0px -5px hsl(225, 21%, 49%)';
lastKey.style.color = 'white';
lastKey.style.boxShadow = 'inset -0px -5px hsl(6, 70%, 34%)';
lastKey.style.backgroundColor = 'hsl(6, 63%, 50%)';
});


secondThemeBtn.addEventListener('change', () => { ballBtn.style.left = '38px';
bodyBackgroundColor.style.backgroundColor = 'hsl(0, 0%, 90%)';
bodyBackgroundColor.style.color = 'black';
document.querySelector('.toggle-btn').style.backgroundColor='hsl(0, 5%, 81%)';
document.querySelector('.calc').style.backgroundColor='hsl(0, 0%, 93%)';
ballBtn.style.backgroundColor = 'hsl(25, 98%, 40%)';
document.querySelector('.grid-container').style.backgroundColor = 'hsl(0, 5%, 81%)';
/*buttonKey.style.backgroundColor = 'hsl(45, 7%, 89%)';
buttonKey.style.boxShadow = 'inset -0px -3px gray';
buttonKey.style.color = 'hsl(221, 14%, 31%)';*/
document.querySelector('.remove').style.backgroundColor = 'hsl(185, 42%, 37%)';
document.querySelector('.remove').style.boxShadow = 'inset -0px -5px hsl(185, 58%, 25%)';
document.querySelector('.reset').style.backgroundColor = 'hsl(185, 42%, 37%)';
document.querySelector('.reset').style.boxShadow = 'inset -0px -5px hsl(185, 58%, 25%)';
document.querySelector('.nine').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.nine').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.nine').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.eight').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.eight').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.eight').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.seven').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.seven').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.seven').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.six').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.six').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.six').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.five').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.five').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.five').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.four').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.four').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.four').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.three').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.three').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.three').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.two').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.two').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.two').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.one').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.one').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.one').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.zero').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.zero').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.zero').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.minus').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.minus').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.minus').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.add').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.add').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.add').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.divide').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.divide').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.divide').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.multiply').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.multiply').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.multiply').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.decimal').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.decimal').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.decimal').style.color = 'hsl(52, 100%, 62%)';
lastKey.style.color = 'white';
lastKey.style.boxShadow = 'inset -0px -5px hsl(25, 99%, 27%)';
lastKey.style.backgroundColor = 'hsl(25, 98%, 40%)';
});

thirdThemeBtn.addEventListener('change', () => { ballBtn.style.left = '72px';
bodyBackgroundColor.style.backgroundColor = 'hsl(268, 75%, 9%)';
bodyBackgroundColor.style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.toggle-btn').style.backgroundColor='';
document.querySelector('.calc').style.backgroundColor='hsl(268, 71%, 12%)';
ballBtn.style.backgroundColor = 'hsl(176, 100%, 44%)';
document.querySelector('.grid-container').style.backgroundColor = 'hsl(268, 71%, 12%)';
document.querySelector('.nine').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.nine').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.nine').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.eight').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.eight').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.eight').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.seven').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.seven').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.seven').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.six').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.six').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.six').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.five').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.five').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.five').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.four').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.four').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.four').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.three').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.three').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.three').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.two').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.two').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.two').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.one').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.one').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.one').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.zero').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.zero').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.zero').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.minus').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.minus').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.minus').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.add').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.add').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.add').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.divide').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.divide').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.divide').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.multiply').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.multiply').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.multiply').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.decimal').style.backgroundColor = 'hsl(268, 47%, 21%)'
document.querySelector('.decimal').style.boxShadow = 'inset -0px -5px hsl(290, 70%, 36%)';
document.querySelector('.decimal').style.color = 'hsl(52, 100%, 62%)';
document.querySelector('.remove').style.backgroundColor = 'hsl(281, 89%, 26%)';
document.querySelector('.remove').style.boxShadow = 'inset -0px -5px hsl(285, 91%, 52%)';
document.querySelector('.reset').style.backgroundColor = 'hsl(281, 89%, 26%)';
document.querySelector('.reset').style.boxShadow = 'inset -0px -5px hsl(285, 91%, 52%)';
lastKey.style.color = 'hsl(290, 70%, 36%)';
lastKey.style.boxShadow = 'inset -0px -5px hsl(177, 92%, 70%)';
lastKey.style.backgroundColor = 'hsl(176, 100%, 44%)';

});